CREATE TABLE IF NOT EXISTS pending_tools (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT NOT NULL,
  url TEXT,
  github_url TEXT,
  category TEXT,
  license TEXT,
  language TEXT,
  hardware TEXT,
  deployment TEXT,
  model_format TEXT,
  maturity TEXT,
  featured INTEGER DEFAULT 0,
  popularity_score INTEGER DEFAULT 0,
  date_added TEXT,
  last_updated TEXT,
  logo_source TEXT DEFAULT 'google',
  logo_r2_key TEXT,
  github_data TEXT,
  status TEXT DEFAULT 'pending',
  submitted_at TEXT,
  reviewed_at TEXT
);
