ALTER TABLE pending_tools ADD COLUMN plain_description TEXT;
ALTER TABLE pending_tools ADD COLUMN technical_description TEXT;
ALTER TABLE pending_tools ADD COLUMN commercial_use INTEGER;
ALTER TABLE pending_tools ADD COLUMN setup_difficulty TEXT;
ALTER TABLE pending_tools ADD COLUMN use_cases TEXT;
ALTER TABLE pending_tools ADD COLUMN personas TEXT;
ALTER TABLE pending_tools ADD COLUMN features TEXT;
ALTER TABLE pending_tools ADD COLUMN works_with TEXT;
ALTER TABLE pending_tools ADD COLUMN docs_url TEXT;
ALTER TABLE pending_tools ADD COLUMN community_guides TEXT;
ALTER TABLE pending_tools ADD COLUMN community_notes TEXT;
ALTER TABLE pending_tools ADD COLUMN min_ram_gb INTEGER;
ALTER TABLE pending_tools ADD COLUMN recommended_ram_gb INTEGER;
ALTER TABLE pending_tools ADD COLUMN telemetry TEXT DEFAULT 'None';
ALTER TABLE pending_tools ADD COLUMN offline_after_setup INTEGER DEFAULT 1;
ALTER TABLE pending_tools ADD COLUMN paid_support INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN gui_available INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN docker_available INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN openai_api INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN rest_api INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN fine_tuning INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN quantization INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN community_notes_count INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN community_guides_count INTEGER DEFAULT 0;
ALTER TABLE pending_tools ADD COLUMN last_verified TEXT;
