export const COMPARE_FIELD_KEYS: { label: string; value: string }[] = [
  { label: 'License', value: 'license' },
  { label: 'Commercial Use', value: 'commercial_use' },
  { label: 'Setup Difficulty', value: 'setup_difficulty' },
  { label: 'Popularity Score', value: 'popularity_score' },
  { label: 'Last Updated', value: 'last_updated' },
  { label: 'OpenAI API', value: 'openai_api' },
  { label: 'REST API', value: 'rest_api' },
  { label: 'Fine-tuning', value: 'fine_tuning' },
  { label: 'Quantization', value: 'quantization' },
  { label: 'Docker Available', value: 'docker_available' },
  { label: 'GUI / No-code', value: 'gui_available' },
  { label: 'Offline After Setup', value: 'offline_after_setup' },
  { label: 'Telemetry', value: 'telemetry' },
  { label: 'Minimum RAM', value: 'min_ram_gb' },
  { label: 'Recommended RAM', value: 'recommended_ram_gb' },
  { label: 'Hardware', value: 'hardware' },
  { label: 'Deployment', value: 'deployment' },
  { label: 'Model Format', value: 'model_format' },
  { label: 'Language', value: 'language' },
  { label: 'Maturity', value: 'maturity' },
  { label: 'Paid Support', value: 'paid_support' },
  { label: 'Features', value: 'features' },
  { label: 'Use Cases', value: 'use_cases' },
  { label: 'Personas', value: 'personas' },
  { label: 'GitHub URL', value: 'github_url' },
  { label: 'Docs URL', value: 'docs_url' },
  { label: 'Community Notes', value: 'community_notes_count' },
  { label: 'Community Guides', value: 'community_guides_count' },
  { label: 'Tag', value: 'tag' },
  { label: 'Featured', value: 'featured' },
  { label: 'Date Added', value: 'date-added' },
];
